modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory
license="All rights reserved"
issueTrackerURL="https://github.com/Silverminer007/MoreOre-1.16/issues" #optional
[[mods]] #mandatory
modId="moreore" #mandatory
version="${version}" #mandatory
displayName="MoreOre" #mandatory
updateJSONURL="https://github.com/Silverminer007/MoreOre-1.16/raw/master/updateJSON.json" #optional
displayURL="https://github.com/Silverminer007/MoreOre-1.16/" #optional
#logoFile="moreore.png" #optional
credits="" #optional
# A text field displayed in the mod UI
authors="Silverminer007" #optional
description='''
This Mod add many Ores, Tools and many other features.
Have fun with it!

For More info look in the changelog in UpdateJSON on my GitHub!
'''


# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.examplemod]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # A display name for the mod
    displayName="Forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[34,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    # A display name for the mod
    displayName="Minecraft" #mandatory
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
